inherit_from: .rubocop_todo.yml
require: rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
